# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.7.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: haybrad@live.co.uk
author_name: amory
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: Example-Algorand-App-contracts

